### ISSUE TITLE
Imagem menu mob

### ISSUE THREAD

**Issue by takeahero** [marcelowcyon/Portfolio#1]
Encontrei os arquivos nomeados como:
Menu.svg e outro como menuu.svg
Na pasta img 

O endereço para a imagem em índex.html está nomeada como
menu.svg

Não seria o motivo para a imagem do menu mob não carregar? 

O projeto está incrível! Parabéns!

**Comment by cadeMeuCode** [comment]
...
<img id="menu_burguer" class="menu_svg" src="img/menu_certo.svg" alt="imagem do menu" onclick="clickMenu()">
...

e se talvez o endereço fosse passado dessa maneira, será que não pode concertar esse erro?
